### ISSUE TITLE
util.go

### ISSUE THREAD

**Issue by weijunzhe** [Greyh4t/util#1]
引用里面的方法时，Bytes报错

..\github.com\Greyh4t\util\util.go:185:53: simplifiedchinese.GB18030.NewDecoder().Bytes undefined (type transform.Transformer has no field or method Bytes)

**Comment by Greyh4t** [comment]
> 引用里面的方法时，Bytes报错
> 
> ..\github.com\Greyh4t\util\util.go:185:53: simplifiedchinese.GB18030.NewDecoder().Bytes undefined (type transform.Transformer has no field or method Bytes)

是哪个版本的golang
